#!/usr/bin/env ruby
# frozen_string_literal: true

require "cri"

require "redfish_tools/cli/serve"

main = Cri::Command.define do
  name        "redfish"
  usage       "redfish command [options and arguments]"
  description "Collection of tools for working with Redfish service"

  run { |_opts, _args| puts(command.help) }
  subcommand Cri::Command.new_basic_help
end

main.define_command do
  name        "serve"
  usage       "serve [options] recording"
  summary     "serve Redfish service recording"

  optional :p, :port, "port to listen on", default: 8000

  runner RedfishTools::Cli::Serve
end

main.run(ARGV)
